#!/bin/zsh
# Warn before pushing to protected branches
# Make script executable with chmod +x pre-push
# Bypass with git push --no-verify

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(main|master)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
  echo "Warning: you are on $BRANCH."
  read "REPLY?Are you sure you want to push this upstream? (y/N): " < /dev/tty
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    exit 0
  fi
  echo "Push aborted."
  exit 1
fi
exit 0
