BG_COLOR="#1A1D23"
ACTIVE_COLOR="#b4befe"
INACTIVE_COLOR="#6c7086"
TEXT_COLOR="#cdd6f4"
ACCENT_COLOR="#b4befe"

unbind r
bind r source-file ~/.config/tmux/tmux.conf # Reload the config file

# Set prefix key
set -g prefix C-s

# Use Zsh's vi mode hooks
setw -g mode-keys vi

# Start windows numbering at 1
set -g base-index 1

# Start panes numbering at 1
setw -g pane-base-index 1

# Optional: Reorder windows automatically when one is closed
set-option -g renumber-windows on

# Detect Zsh mode changes and update the cursor
bind-key -T vi-command Escape run-shell "printf '\e[2 q'"
bind-key -T vi-insert Escape run-shell "printf '\e[2 q'"
bind-key -T vi-insert Enter run-shell "printf '\e[6 q'"

# Vim-like copy mode bindings
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'r' send -X rectangle-toggle

# Copy to system clipboard
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Session Rename using Prefix + R
bind R command-prompt -I "#{session_name}" "rename-session '%%'"

# Set terminal color support
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',xterm-256color:RGB'

set -g mouse on              # Enable mouse support
set -g focus-events on       # Enable focus events for better Vim integration
set -g set-clipboard on      # Enable system clipboard
set -g detach-on-destroy off # Don't exit from tmux when closing a session


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'


# Set this here to avoid tmux-minimal-theme overriding the position.
set -g status-style "bg=default,fg=$TEXT_COLOR"
set -g status-position top
set -g status on
set -g status-interval 5
set -g status-justify left

set -g status-right "\
#[fg=$ACCENT_COLOR] #[fg=$TEXT_COLOR]#([ #{pane_current_path} = $HOME ] && echo '~' || basename #{pane_current_path})"

set -g message-style "bg=default,fg=$TEXT_COLOR,bold"
set -g message-command-style "bg=default,fg=$TEXT_COLOR,bold"

set -g window-status-format "#[fg=$INACTIVE_COLOR,bg=default] #I:#W "
set -g window-status-current-format "#[fg=$ACTIVE_COLOR,bg=default,bold] #I:#W "

# Emulate padding by setting another status bar bellow the actual one
set -g status 2
set -g 'status-format[1]' ''

# Initialise TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
